Repository archettialberto/fpboost, pull requests merged in 2024-10, with the labels that each got.

#2 Support for automated Pypi release
  .github/workflows/test.yaml
  .github/workflows/test_build_release.yaml
  README.md
  poetry.lock
  pyproject.toml
Labels: enhancement

#4 Trigger workflow on tags
  .github/workflows/test_build_release.yaml
Labels: enhancement

#5 Update GitHub Actions workflow to publish to PyPI on tag pushes only
  .github/workflows/test_build_release.yaml
Labels: bug

#6 Update README with coverage
  .github/workflows/test_build_release.yaml
  README.md
Labels: documentation

#7 Update workflow name and badges in README
  .github/workflows/test_build_release.yaml
  README.md
Labels: documentation
